dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.14.x"

before_install:
- sudo apt-get update
- sudo apt-get -y install httpie jq

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- bash scripts/getnomad.sh
- bash scripts/getvault.sh


before_script:
- bash scripts/start-nomad.sh

script:
- make vet
- NOMAD_TOKEN=$(cat /tmp/nomad-test.token) make testacc

after_scripts:
- bash scripts/stop-nomad.sh

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  - GO111MODULE=on
